repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: a9a8a861f30ed207ead7d5a3b7e8032283ba5da7  # frozen: v23.1.2
    hooks:
      - id: clang-format
        files: ^.+.proto$
        args: [-i, -style=file]

  - repo: https://github.com/codespell-project/codespell
    rev: 57b21406f092110c18776e39b0bda50d37c945c8  # frozen: v2.4.3
    hooks:
      - id: codespell
        args: ["-L", "Synopsys,synopsys"]

  - repo: https://github.com/yoheimuta/protolint
    rev: c5433e2d6826441fc6150e7eb0ff5ad568100ad5  # frozen: v0.58.0
    hooks:
      - id: protolint

  - repo: https://github.com/ansys/pre-commit-hooks
    rev: 55c5b6a5439abd847613579c6924da750e8b78b2  # frozen: v0.8.0
    hooks:
      - id: add-license-headers
        files: '(src/|setup).*(\.py|\.proto)$'
        args:
          - --start_year=2023
          - --custom_license=Apache-2.0
