# Copyright (C) 2023 - 2026 Synopsys, Inc. and ANSYS, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Installation file for the ``ansys-api-cfx`` package"""

import os
from datetime import datetime

import setuptools

from ansys.tools.protoc_helper import CMDCLASS_OVERRIDE

# The README file contains build and deployment instructions that we don't want to include
# in the PyPI README. Set up the long_description manually.
long_description = """### ansys-api-cfx gRPC Interface Package

This Python package contains the auto-generated gRPC Python interface files for CFX.

#### Installation

Provided that these wheels have been published to the public PyPI, they can be installed with:

```
pip install ansys-api-cfx
```
"""

product = "cfx"
library = ""
package_info = ["ansys", "api", product, library, "v0"]
HERE = os.path.abspath(os.path.dirname(__file__))
with open(os.path.join(HERE, "src", "ansys", "api", product, library, "VERSION"), encoding="utf-8") as f:
    version = f.read().strip()

package_name = "ansys-api-cfx"
dot_package_name = ".".join(filter(None, package_info))

description = f"Autogenerated python gRPC interface package for {package_name}, built on {datetime.now().strftime('%H:%M:%S on %d %B %Y')}"

if __name__ == "__main__":
    setuptools.setup(
        name=package_name,
        version=version,
        author="Synopsys, Inc. and ANSYS, Inc.",
        author_email="pyansys-core@synopsys.com",
        maintainer="Synopsys, Inc. and ANSYS, Inc.",
        maintainer_email="pyansys-core@synopsys.com",
        description=description,
        long_description=long_description,
        long_description_content_type="text/markdown",
        url=f"https://github.com/ansys-internal/{package_name}",
        license="Apache-2.0",
        python_requires=">=3.9,<4.0",
        install_requires=["grpcio~=1.30", "protobuf>=3.19,<7"],
        package_dir={"": "src"},
        packages=setuptools.find_namespace_packages("src", include=("ansys.*",)),
        package_data={
            "": ["*.proto", "*.pyi", "py.typed", "VERSION"],
        },
        entry_points={
            "ansys.tools.protoc_helper.proto_provider": [
                f"{dot_package_name}={dot_package_name}"
            ],
        },
        cmdclass=CMDCLASS_OVERRIDE
    )
