// Copyright (C) 2023 - 2026 Synopsys, Inc. and ANSYS, Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package grpcRemoting;
service Events {
  rpc BeginStreaming(BeginStreamingRequest) returns (stream BeginStreamingResponse) {}
}

message BeginStreamingRequest {
}

/**
 * Event at end of the time step.
 */
message TimestepEndedEvent {
  sint64 index = 1;  // Time step index.
  double size = 2;   // Time step size.
}

/**
 * Event at end of the iteration.
 */
message IterationEndedEvent {
  sint64 index = 1;  // Iteration index
}

/**
 * Event at start of calculation.
 */
message CalculationsStartedEvent {
}

/**
 * Event at end of calculation.
 */
message CalculationsEndedEvent {
}

/**
 * Event at start of def read.
 */
message AboutToReadDefEvent {
  string deffilepath = 1;  // Def file path.
}

/**
 * Event after def is read.
 */
message DefReadEvent {
  string deffilepath = 1;  // Def file path.
}

/**
 * Event at res read.
 */
message ResReadEvent {
  string resfilepath = 1;  // Res file path.
}

/**
 * Event at solution initialization.
 */
message InitializedEvent {
}

/**
 * Event during solution progress.
 */
message ProgressEvent {
  string message = 1;          // Progress Message.
  sint32 percentComplete = 2;  // Percent completed.
}

/*
 * Event when fatal error encountered
 */
message ErrorEvent {
  string message = 1;
  sint32 errorCode = 2;
}

message BeginStreamingResponse {
  oneof as {
    AboutToReadDefEvent abouttoreaddefevent = 1;
    DefReadEvent defreadevent = 2;
    InitializedEvent initializedevent = 4;
    ResReadEvent resreadevent = 6;
    IterationEndedEvent iterationendedevent = 8;
    TimestepEndedEvent timestependedevent = 10;
    CalculationsStartedEvent calculationsstartedevent = 11;
    CalculationsEndedEvent calculationsendedevent = 12;
    ProgressEvent progressevent = 20;
    ErrorEvent errorevent = 21;
  }
}
